### ISSUE TITLE
객채

### ISSUE THREAD

**Issue by jiyeong1004** [TeMlN/TIL#2]
안녕하세요! 글 너무 잘 읽었습니다👍
초면에 실례일 수도 있겠지만
[OOP (**객채** 지향 프로그래밍)]와 [좋은 **객채** 지향 프로그래밍을 위한 다섯가지 원칙 SOLID]에서
**객채**를 **객체**로 수정해 주시면 더 좋을 것 같아요 😉

<img width="380" alt="객채" src="https://user-images.githubusercontent.com/51290739/124055403-cada0980-da5e-11eb-91a5-8fae70687602.png">

**Comment by TeMlN** [comment]
안녕하세요 jiyeong1004님! 너무 정신없이 적다보니 오타가 난거 같아요 죄송합니다 ㅠㅠ 이슈 본대로 즉시 수정 하였습니다 감사합니다!
